name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Source branch to cherry-pick commits from'
        required: true
        default: 'dev'
        type: string
      target-branch:
        description: 'Target branch to create the release from'
        required: true
        default: 'main'
        type: choice
        options:
          - main
      mergedSince:
        description: 'Include PRs merged since date (format: YYYY-MM-DDTHH:MM:SSZ)'
        required: false
        default: ''
      mergedUntil:
        description: 'Include PRs merged until date (format: YYYY-MM-DDTHH:MM:SSZ)'
        required: false
        default: ''
      includePrIds:
        description: 'Comma-separated list of PR IDs to include'
        required: false
        default: ''
      excludePattern:
        description: 'Comma-separated list of title patterns to exclude'
        required: false
        default: ''
      enforceVersion:
        description: 'Enforcing a specific version (not cool but anyway)'
        required: false
env:
  SOURCE_BRANCH: ${{ github.event.inputs.source-branch }}
  TARGET_BRANCH: ${{ github.event.inputs.target-branch }}
  TZ: Europe/Istanbul
permissions: write-all
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Critical - fetch full history
          token: ${{ secrets.PR_CREATION_TOKEN }}

      - name: Create Release Branch
        uses: sulhadin/create-release-branch@v1
        with:
          source-branch: ${{ github.event.inputs.source-branch }}
          target-branch: ${{ github.event.inputs.target-branch }}
          github-token: ${{ secrets.PR_CREATION_TOKEN }}
          branch-prefix: "release/"
          merged-since: ${{ github.event.inputs.mergedSince }}
          merged-until: ${{ github.event.inputs.mergedUntil }}
          include-pr-ids: ${{ github.event.inputs.includePrIds }}
          exclude-pattern: ${{ github.event.inputs.excludePattern }}
          version-file: "version.json"
          enforce-version: ${{ github.event.inputs.enforceVersion }}
          repo-path: "sulhadin/create-release-branch"
          verbose: 'false'